### ISSUE TITLE
Can't open the menu

### ISSUE THREAD

**Issue by adhdirl** [WildfireRomeo/WildfireFemaleGenderMod#105]
I'm trying to get the mod to work with the Better MC fabric modpack and its the only mod I've added myself, I already checked and there arent any other items applied to g so idk whats wrong, the version I'm using is 1.19.2 3.0.1

**Comment by adhdirl** [comment]
update nvm i just rebounded the key and it worked

**Comment by Aceplante2** [comment]
you can close this
