### ISSUE TITLE
[OF bug, low priority][1.19.2] Compatible issue with Cute Mob Models resourcepacks

### ISSUE THREAD

**Issue by rainbowflesh** [WildfireRomeo/WildfireFemaleGenderMod#106]
Load mod with CMM enabled will make game crash on start, but in game change resource pack will not crash and running good.

Such a big problem that being unable to view both mob tits and player tits at the same time is the greatest sorrow of ALL MANKIND.

[crash-2023-03-14_00.25.49-client.txt](https://github.com/WildfireRomeo/WildfireFemaleGenderMod/files/10959567/crash-2023-03-14_00.25.49-client.txt)

test in forge 43.2.6 & optifine u_i1.

**Comment by ChaosDogG** [comment]
It has been known that OptiFine (OF) likes to break things within modded instances. Have you tried loading the game with shaders off and the pack on?

**Comment by rainbowflesh** [comment]
> It has been known that OptiFine (OF) likes to break things within modded instances. Have you tried loading the game with shaders off and the pack on?

Tried on, no crash 🤔. I see, this bug confirmed from upstream OF. I think I should keep this issue open and follow up conversation until OF fix the bug.
