### ISSUE TITLE
Incompatible with Valhelsia 5

### ISSUE THREAD

**Issue by aCattywampus** [WildfireRomeo/WildfireFemaleGenderMod#109]
[crash-2023-03-23_18.25.12-client.txt](https://github.com/WildfireRomeo/WildfireFemaleGenderMod/files/11056896/crash-2023-03-23_18.25.12-client.txt)

This is the crash file. All I can really say is that it crashed, and even with the mod Not Enough Crashes

**Comment by WildfireRomeo** [comment]
Running 1.19.3 mod version in a 1.19.2 environment.
