### ISSUE TITLE
Crash on 1.19.4, any way to resolve? 

### ISSUE THREAD

**Issue by diademiemi** [WildfireRomeo/WildfireFemaleGenderMod#110]
Hey! I get the following error on 1.19.4 with only Fabric, latest Fabric API and Female-Gender-Mod-fabric-1.19.3-3.0.1.
```
Caused by: java.lang.NoSuchFieldError: field_6249
	at com.wildfire.physics.BreastPhysics.update(BreastPhysics.java:119) ~[Female-Gender-Mod-fabric-1.19.3-3.0.1(1).jar:?]
	at net.minecraft.class_1657.tickWildfire(class_1657.java:2905) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.handler$zkc000$wildfire_gender$onTick(class_1657.java:2895) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.method_5773(class_1657.java:331) ~[client-intermediary.jar:?]
	at net.minecraft.class_742.method_5773(class_742.java:73) ~[client-intermediary.jar:?]
	at net.minecraft.class_746.method_5773(class_746.java:217) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_18646(class_638.java:269) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:488) ~[client-intermediary.jar:?]
	... 13 more
```
I've attached the full log here:
[errorlog.txt](https://github.com/WildfireRomeo/WildfireFemaleGenderMod/files/11092809/errorlog.txt)

I haven't worked with Fabric before, so I'm unsure if this is something I could fix.

**Comment by Kichura** [comment]
Because 1.19.4 support is not a thing yet, Please be patient about it.

**Comment by diademiemi** [comment]
Alright, is there a tracker on what's necessary to update it? I'd be open to try to contribute to an update

**Comment by Kichura** [comment]
The only hint i can give at the moment is updating mixins to work properly in 1.19.4 but this possibly might apply to all scripts if it's super incompatible. (1.19.3 hit us hard last time with their changes)

**Comment by diademiemi** [comment]
Just got it compiled and running, seems to work!

1.19.4 removed the limbAngle and limbDistance properties of entities and uses a LimbAnimator now. I can't quite figure out where to get them now. 
I've replaced it with `limbAnimator.getPos()` for the angle and `limbAnimator.getSpeed()` for the distance. The end result looks exactly as I'd expect from this mod, was just feeding it any data related to player movement here enough?

You can view my changes at https://github.com/diademiemi/WildfireFemaleGenderMod/commit/d12a9be22569ab454bb61a667c5b3fde8209ad15

What's the limbAngle and limbDistance for? I'm not quite sure what it does in the original code and whether these changes are okay.

**Comment by diademiemi** [comment]
They don't exist anymore in 1.19.4, see https://maven.fabricmc.net/docs/yarn-1.19.4+build.1/net/minecraft/entity/LivingEntity.html, and LimbAnimator doesn't seem to map 1:1 https://maven.fabricmc.net/docs/yarn-1.19.4+build.1/net/minecraft/entity/LimbAnimator.html

**Comment by diademiemi** [comment]
Even without using those fields the animation does still look correct. Is there any other reason for having specifically limbAngle and limbDistance or are these inputs fine too? 

![Peek 2023-03-28 21-08](https://user-images.githubusercontent.com/56408488/228342241-28d945eb-e522-4c14-92ea-bb8c0fafd2ab.gif)

**Comment by celestialfault** [comment]
> Is there any other reason for having specifically limbAngle and limbDistance or are these inputs fine too?

No reason for these specifically other than that's just what they're called in 1.19.3; the changes in .4 are largely just 1:1 renames while also being moved to their own class (for whatever stupid reason Mojang can come up with this time for making breaking changes in yet another patch release).

**Comment by Kichura** [comment]
> Just got it compiled and running, seems to work!
> 
> 1.19.4 removed the limbAngle and limbDistance properties of entities and uses a LimbAnimator now. I can't quite figure out where to get them now. I've replaced it with `limbAnimator.getPos()` for the angle and `limbAnimator.getSpeed()` for the distance. The end result looks exactly as I'd expect from this mod, was just feeding it any data related to player movement here enough?
> 
> You can view my changes at [diademiemi@d12a9be](https://github.com/diademiemi/WildfireFemaleGenderMod/commit/d12a9be22569ab454bb61a667c5b3fde8209ad15)
> 
> What's the limbAngle and limbDistance for? I'm not quite sure what it does in the original code and whether these changes are okay.
> 
> Let me know if I should create a PR (one for Fabric and one for Forge I'm guessing?)

Sent out a PR since some small details are incorrect, PR can be created after merge there.
