### ISSUE TITLE
1.8.9 when

### ISSUE THREAD

**Issue by AXDWT** [WildfireRomeo/WildfireFemaleGenderMod#114]
the title says at all. i play 1.8.9 the most. and then i have nothing to explain more since im lazy to type :trollface:

**Comment by GayRedPanda** [comment]
There will (most likely) never be an official 1.8 version of the mod

**Comment by PumpkinXD** [comment]
> i have nothing to explain more since im lazy to type

lol, 1.8.9 is dead version and for vanilla pvp/minigame

**Comment by diademiemi** [comment]
> the title says at all. i play 1.8.9 the most. and then i have nothing to explain more since im lazy to type :trollface:

then make it yourself? don't expect others to do tremendous work for you to port a mod for free

**Comment by Kichura** [comment]
Not happening, period.

**Comment by aricloverEXTRA** [comment]
## Update 3: The showcase of some of the features in the 1.8.9 mod so far.
Recently started continuing the 1.8.9 version.
Got almost fully functioning physics, with the exception of physics not affecting rotation of the player model via mouse.
And if you had noticed, this is based on **Female Gender Mod - 5.0.0 Beta 2**, so I'm gonna try to add more features for the 1.8.9 version.

https://github.com/user-attachments/assets/4e64add5-7c00-4068-a31d-d685935342fc

#### Here's the key binds too!
<img width="720" height="349" alt="Image" src="https://github.com/user-attachments/assets/fb085f06-53cc-4722-8d4e-5846ca0288a5" />

**Comment by aricloverEXTRA** [comment]
Oh thanks Kichura, yeah some skins do appear wrong because it was made very differently in that version (1.8.9/1.12.2) of the mod and will do some fixes for it that when I mention it in update 5!
