### ISSUE TITLE
Invisible entities when used with Essential

### ISSUE THREAD

**Issue by Punkin-GH** [WildfireRomeo/WildfireFemaleGenderMod#129]
When using both Essential and Wildfire's Female Gender Mod, all entities of any type (mobs, items, chests, beds, etc) all become totally invisible. Fully functional, and very much there, but invisible.

- Minecraft version: 1.16.5
- Forge version: 36.2.39
- Essential version: "12933+deploy-staging+gf941de5ac" (according to Minecraft's mod menu)
- Wildfire's Female Gender Mod version: 2.8

**Comment by TransBluelight** [comment]
Don't use essential. It's bad, proprietary and mods break with it often plus Wildfire herself said that the 1.16.5 version is no longer supported so likely this won't get fixed

**Comment by Punkin-GH** [comment]
ah, damn. I hadn't seen that the 1.16 version wasn't supported, and I was hoping to keep using essential since it allows LAN multiplayer without hamachi or anything

**Comment by TransBluelight** [comment]
If you can just run the server yourself or if you're down for torturing yourself with (probably) bad TPS use aternos

**Comment by Punkin-GH** [comment]
Nah, Aternos sucks because you can only use approved mods, and I like to make my own mods. Plus, imo LAN is just generally easier to use when you're only playing with a few people. Using hamachi isn't the end of the world, so i'll just cut my losses

**Comment by ArcticWah** [comment]
If you're using Essential just for that and are willing to upgrade to a newer version, which I doubt, I'd recommend e4mc for the LAN worlds. It might not be for everyone, but it has gotten the job done for me. If you wanna stay on 1.16.5 I don't really think there is anything you can do except throw out one of the mods

**Comment by Punkin-GH** [comment]
I have dozens of modpacks for different versions, but this one needs to stay on 1.16.5. I've made peace with just having to toss one of the mods. It's sad, but, being a modpack dev, i'm used to things like that by now
