### ISSUE TITLE
Crash when interacting with modded armors (1.18.1)

### ISSUE THREAD

**Issue by Shedao-Shai** [WildfireRomeo/WildfireFemaleGenderMod#14]
Forge version: 39.0.88
Wildfire version: 2.8.1

Crash log: https://gist.github.com/Shedao-Shai/ea9324afb323b5707d7b679d880a8af1
Debug log: https://gist.github.com/Shedao-Shai/a5519f74a5b4e9849b88304b53882e7c
Latest log: https://gist.github.com/Shedao-Shai/67c78ec9af880094516ff258613b3f6f

What happens: when wildfire gender is installed, rendering any piece of modded armor on the chest and sometimes on the head causes a crash. This does _not_ happen if the armor is not rendered, wearing it by itself is fine, but as soon as the player goes into third person or opens their inventory the game will crash and brick the world if the player was in third person.

I have tested this interaction with mystical agriculture and tinkers construct armors, and I expect that the same will occur with any other mods armors.

**Comment by pupnewfster** [comment]
I am fairly certain this is fixed in dev as part of the changes I made in #3

**Comment by Shedao-Shai** [comment]
Beautiful! Cant wait for it to drop for 1.18.2, this is a really well-done mod

**Comment by WildfireRomeo** [comment]
Closed as this is most likely fixed in the coming update.
