### ISSUE TITLE
How to enable breast jiggle physics when I have armor

### ISSUE THREAD

**Issue by Lepre-CHAU-n** [WildfireRomeo/WildfireFemaleGenderMod#142]
I'm trying to modify your mod because when you wear armor, it stops them from jiggling completely which is fine in vanilla.
However when I’m using the flower armor texture pack it looks really off, s o I want to remove that feature entirely and make it so the breast always jiggle.
I am unsure how to adjust the current code and return it to a working jar. Any pointers would help. Thanks a lot

**Comment by WildfireRomeo** [comment]
Re-added button toggle to override armor physics recently again.
