### ISSUE TITLE
Fake players?

### ISSUE THREAD

**Issue by Aceplante2** [WildfireRomeo/WildfireFemaleGenderMod#143]
On hypixel there are a ton of fake players named !A-4 etc, which makes it difficult to find the real players, especially when people are quickly leaving and joining. Can there be an option to order them oldest to newest or alphabetically?

**Comment by WildfireRomeo** [comment]
closing as player list has been removed in recent update.

**Comment by Aceplante2** [comment]
I still see the fake players?

**Comment by WildfireRomeo** [comment]
The player list was removed in the most recent update, not sure why you'd still be seeing them.

**Comment by Aceplante2** [comment]
Perhaps becuase it still exists in 1.18.2? I assume said update was not made for 1.18.2, but I'm kind of glad becuase how else would you edit players without the menu?
