### ISSUE TITLE
1.19.2 Crash On Startup

### ISSUE THREAD

**Issue by ShadowRocks2** [WildfireRomeo/WildfireFemaleGenderMod#145]
i dont know whats causing this, could be another mod conflicting with it but disabling this mod lets it launch so here is the error log part that says its wildfire causing it

https://mclo.gs/WSzcPhP

and the full log as well if needed

https://mclo.gs/FTF9Vhp

**Comment by celestialfault** [comment]
You're using the wrong version - if you're downloading from Modrinth, you'll want to use [this version](https://modrinth.com/mod/female-gender/version/3.0.0-1.19-fabric) instead, as the 1.19.3 version is incorrectly tagged as working on 1.19.2 when it shouldn't.

**Comment by ShadowRocks2** [comment]
> You're using the wrong version - if you're downloading from Modrinth, you'll want to use [this version](https://modrinth.com/mod/female-gender/version/3.0.0-1.19-fabric) instead, as the version you're using is incorrectly tagged as working on 1.19.2 when it shouldn't.

thank you, that fixed it, also just realize the file said 1.19.3, they should fix that

**Comment by ShadowRocks2** [comment]
modrinth show version 1.19.3-3.0.1 as being compatible with 1.19.2, it is not version 3.0.0-1.19-fabric is.
