### ISSUE TITLE
[PR permission request] Better jiggle physics

### ISSUE THREAD

**Issue by nopeless** [WildfireRomeo/WildfireFemaleGenderMod#146]
I have reworked the jiggle physics a few months ago, and I would have submitted a PR but the code base was going through fabric 1.19.4/1.20 changes so I ignored it for a while

The new physics engine implements these:

- No out of bounds (breasts won't poke out of the player's body)
- Falling and jumping are based off of actual acceleration values instead of timers
- Rotating breast boxes (pitch)

This simulates a much more natural movement, but I believe this is opinionated so I am asking for your opinion as well

## Original

https://github.com/WildfireRomeo/WildfireFemaleGenderMod/assets/38830903/03d78441-dbf5-4b41-bd6d-02bfd39d4a03

## Physics rewrite

https://github.com/WildfireRomeo/WildfireFemaleGenderMod/assets/38830903/685a9227-c3bb-4ef1-9048-b53da50859e5

I am open for discussion

**Comment by WildfireRomeo** [comment]
I know this was a while ago, but if you can still, I would suggest just opening a PR so I can take a look at it and see if it's something I'm interested in implementing.

I have been wanting to revamp the breast physics to be more realistic for a while now, but I haven't had the time to dive into it.

**Comment by nopeless** [comment]
bit busy nowadays. But I will submit a PR on the most recent branch maybe a few weeks later. Thanks for confirming your interest
