### ISSUE TITLE
1.18.2 armor physics not working

### ISSUE THREAD

**Issue by RayJay232** [WildfireRomeo/WildfireFemaleGenderMod#154]
just what the title says

**Comment by WildfireRomeo** [comment]
The "Armor Physics" button toggle (or option was removed in one of those versions if I recall correctly. I'm only supporting the latest versions of the mod officially, so 1.18.2 will not be updated.

I know the armor physics itself was removed before the button was (which caused the button to do nothing for an update or two), but it was removed entirely and re-added in a later version slightly different than it used to behave.
