### ISSUE TITLE
No physics with armor even if setting is enabled

### ISSUE THREAD

**Issue by VIClub** [WildfireRomeo/WildfireFemaleGenderMod#157]
Hello I encountered a problem, the chest does not have physics with the armor even if I activate the parameter which allows it.

**Comment by WildfireRomeo** [comment]
What version of the mod are you running? I think there was a version released between removing it and re-adding it where the toggle was not functional but it was still there.

**Comment by WildfireRomeo** [comment]
Closing as this hasn't been responded to, and there's a new issue opened regarding a similar problem #165.
