### ISSUE TITLE
Opening menu crashes game and may invalidate player data

### ISSUE THREAD

**Issue by bagelBrain** [WildfireRomeo/WildfireFemaleGenderMod#160]
Pressing G exits to menu in servers, in single player it reads "Invalid Player Data" and returns to the _multiplayer_ screen.

![i2addadadasdasdasdasadadadq23mage](https://github.com/WildfireRomeo/WildfireFemaleGenderMod/assets/139088719/7da23e8e-a69d-466c-9244-fb7aa44bd551)

**Comment by WildfireRomeo** [comment]
Crash report please
