### ISSUE TITLE
No physics with armor even if setting is enabled 1.20.1

### ISSUE THREAD

**Issue by LenaTheDeer** [WildfireRomeo/WildfireFemaleGenderMod#165]
On 1.20.1
No physics with armor option doesn't work, if you enable it it just disable itself or just doesn't do anything

https://github.com/WildfireRomeo/WildfireFemaleGenderMod/assets/69579282/0cb9afa4-256a-4af7-ba58-50d2b7584659

for the record this happened on Version 1.20.1 of Minecraft Java edition
i have attached a video, sorry for the low quality and watermark i needed to compress to comply for github

**Comment by pupnewfster** [comment]
As far as I am aware none of the released versions should work on forge or neoforge for 1.20.2 currently? So are you sure your version information is correct as I would expect the mod to not load at all

**Comment by Evaaaaaan** [comment]
hello! it was a type my bad, i have edited it. it was on 1.20.1

**Comment by PeglinX** [comment]
The config is currently bugged. After enabling close the UI. Reopen it and click once on armor physics. It should show disabled but actually be enabled.
 Alternatively go into the .minecraft/config folder then to wildfire female gender and inside the file named with your UUID edit the armor physics variable to true
