### ISSUE TITLE
Idk code and an error happened

### ISSUE THREAD

**Issue by HELpfnjieowfnuio** [WildfireRomeo/WildfireFemaleGenderMod#177]
badically i was just trying it out and i press appearence settings and it crashes saying exit code-1

**Comment by angrydestreyer9** [comment]
In 1.20.4 using the newest version of the mod (1.20.2-3.1) game crashes with exit code 1 and this error

The game crashed whilst mouseclicked event handler
Error: java.lang.IncompatibleClassChangeError: class com.wildfire.gui.WildfireBreastPresetList overrides final method net.minecraft.class_339.method_37020(Lnet/minecraft/class_6382;)V

idk if this is the same issue but as there is no information in this issue I will add this context. 
I also know that I am using the wrong version of minecraft for the mod, however everything else works fine.

**Comment by HELpfnjieowfnuio** [comment]
I decided to change to forge and it fixed it anyways

**Comment by Betawolfy** [comment]
The 1.20.2 mod works fine, you just can't use the menu. But you can use the config file to edit the value.
