### ISSUE TITLE
I don’t know how to get jar file 1.20.4 fabric, give instructions

### ISSUE THREAD

**Issue by verixyt3** [WildfireRomeo/WildfireFemaleGenderMod#183]
I don’t know how to get jar file 1.20.4 fabric, give instructions

**Comment by Betawolfy** [comment]
join the discord, then go check the pins message in [mod-discussion](https://canary.discord.com/channels/820872727539875841/820891107998040064)

**Comment by PeglinX** [comment]
time to close this
