### ISSUE TITLE
Player selection menu does not appear after pressing G 1.20.4

### ISSUE THREAD

**Issue by fnafmare** [WildfireRomeo/WildfireFemaleGenderMod#188]
![image](https://github.com/WildfireRomeo/WildfireFemaleGenderMod/assets/98798098/31df7353-9beb-4309-8520-f75202045268)
After pressing G, only the player settings menu appears. Player selection menu does not appear

**Comment by ArcticWah** [comment]
This is international. It was removed a little while ago and will probably not make comeback
