### ISSUE TITLE
1.21 required on server?

### ISSUE THREAD

**Issue by Aceplante2** [WildfireRomeo/WildfireFemaleGenderMod#189]
Forge 1.20.1

Last time I was told its 'maintained by the community'. What does that mean and why does it not work client side? It used to just fine in 1.18 and before

**Comment by Betawolfy** [comment]
forge is maintained by the community, which means Wildfire, creator of the mod, don't really control the forge version. the community is the one who update to the latest version for forge.
If you want to use the mod in client side, i suggest using Fabric.

**Comment by Aceplante2** [comment]
The modpack I use is forge, so I assume theyre not compatible? So basically what youre saying is the community decided to make the newer versions server side?

**Comment by pupnewfster** [comment]
Update your mod, that bug should be fixed in the last released 1.20.1 version

**Comment by Aceplante2** [comment]
I am on the latest version. 1.20.1-3.0.1
