### ISSUE TITLE
suggestion: the menu should open to configure another player when looking at them

### ISSUE THREAD

**Issue by nopeless** [WildfireRomeo/WildfireFemaleGenderMod#192]
found out the player list has been removed. I think this would be a suitable replacement

**Comment by TransBluelight** [comment]
the reason why this was removed was specifically to not modify other people's genders i.e misrepresenting them or people thinking wrongly of the mod so I doubt wildfire would bring this back

**Comment by nopeless** [comment]
> people thinking wrongly of the mod
I'm not sure what this means but I guess some people just use it on other players who don't want it?

Anyway, didn't know that was the reason. Never thought of it that way.

`Minecraft.getInstance().hitResult instanceof EntityHitResult hit && hit.getEntity() instanceof Player p`

I'll leave this here just in case.
