### ISSUE TITLE
When will the mod for version 1.21 be released?

### ISSUE THREAD

**Issue by lapa3228** [WildfireRomeo/WildfireFemaleGenderMod#193]
Tired of playing without boobs, what should I do? I have been waiting for the release of the mod for a new version for several days, I myself cannot figure out the methods and rewriting the mod for the new version, minecraft simply does not start.

**Comment by sylv256** [comment]
You can use the Ears mod for this actually! It does not have jiggle physics, and they are not detailed, but that's fine for me and most players.
https://ears.unascribed.com/
https://gist.github.com/sylv256/a96b2c369e48ba50d9ed4d175033c693

**Comment by WildfireRomeo** [comment]
Updated to 1.21.
