### ISSUE TITLE
resource pack audio is played with female hurt sound

### ISSUE THREAD

**Issue by GreenDude-2009** [WildfireRomeo/WildfireFemaleGenderMod#198]
i use this mod on fabric 1.20.4, and when i equip a resource pack that changes hurt sounds, it plays with the female hurt sound

**Comment by GreenDude-2009** [comment]
and no, its not above fabric mod resources

**Comment by celestialfault** [comment]
This is intended behavior, the mod's hurt sound plays alongside the vanilla hurt sound instead of replacing it to avoid removing audio cues for how a player is taking damage, such as the separate fire/drowning hurt sounds

**Comment by GreenDude-2009** [comment]
huh???

**Comment by celestialfault** [comment]
Just to clarify, are you referring to the *mods* hurt sounds? If you are, make sure you're replacing the correct files; the relevant files to replace are `female_damage.ogg` *and* `female_damage2.ogg` in `assets/wildfire_gender/sounds/`

**Comment by celestialfault** [comment]
Adding to the above:

> and no, its not above fabric mod resources

Your resource pack must also be *above* mod resources, otherwise the mod's built-in sound files will simply replace the sounds you're trying to use, as the game prioritizes resources from packs further up the list.

**Comment by GreenDude-2009** [comment]
no, is there a way to disable the vanilla hurt sounds on characters with female selected?

**Comment by GreenDude-2009** [comment]
thats what i want

**Comment by WildfireRomeo** [comment]
There is not a way to do this. The way it is currently set up it plays both vanilla hurt sounds and female hurt sounds at the same time.
