### ISSUE TITLE
Fabric 1.20.1 Version not included?

### ISSUE THREAD

**Issue by arcade-smasher** [WildfireRomeo/WildfireFemaleGenderMod#199]
I noticed the 1.20.1 version for fabric is not included in the branches.

**Comment by arcade-smasher** [comment]
Or the 1.20.0, for that matter.

**Comment by Betawolfy** [comment]
The mod is just not officially ported in 1.21 yet.
But, you can check the discord server to get the 1.21 version from the community.
https://canary.discord.com/channels/820872727539875841/820891107998040064/1251937024789844010
