### ISSUE TITLE
[CurseForge Issue Report] Not compatible with LuckPerms

### ISSUE THREAD

**Issue by WildfireRomeo** [WildfireRomeo/WildfireFemaleGenderMod#20]
**DaisukeVN1**

Hey WildfireRomeo,

 
if I install this Mod on my Server then the Mod "LuckPerms" can't load and the Server Crash.

Without your Mod. Everything works fine.

I already ask the Dev from LuckPerms and they mean they can't help me because it's not their fault.

Can you please check why there is a compatibility error? I want to use both but LuckPerms is very important for my project.

Their Mod-Page:

https://www.curseforge.com/minecraft/mc-mods/luckperms

System Data:
Minecraft 1.16.5 - Fabric 0.11.6

Mod Version: 2.7.1

**Comment by Kichura** [comment]
Cannot reproduce this issue on 1.18.2 using latest luckperms and newest compiled version of this mod.
