### ISSUE TITLE
Config: hello?

### ISSUE THREAD

**Issue by Gogo-a** [WildfireRomeo/WildfireFemaleGenderMod#203]
theres no config (that i can find anyways)
ether theres none or im dumb. 
please make a config. thanks.

**Comment by ArcticWah** [comment]
.minecraft/config/WildfireGender/{UUID}.json

**Comment by Gogo-a** [comment]
still dont see it. im on mac. does that effect it?

**Comment by ArcticWah** [comment]
being on Mac doesn't effect it. The structure is the same no matter the operating system

**Comment by catreplicators** [comment]
Also not there for me. The folder /WildfireGender/ is there, but it's empty.

**Comment by Gogo-a** [comment]
same

**Comment by Gogo-a** [comment]
Ive been doing a lot of testing and found once the game has been run, you may access the configs for the duration of the time the game is launched. In this message i have enclosed what the config looks like in VS code, aswell as the file.
![SS1](https://github.com/user-attachments/assets/4284577a-e98e-4d9b-b83d-da1a78920032)
![SS2](https://github.com/user-attachments/assets/80658893-e7b8-49f2-8235-5435764826f9)

**Comment by Gogo-a** [comment]
I was on 1.21 and the most recent update.
