### ISSUE TITLE
1.21 problem i dont know

### ISSUE THREAD

**Issue by MaxTheBomber** [WildfireRomeo/WildfireFemaleGenderMod#204]
The list of players does not open. It immediately shows my character and I can't change the gender of others. What should I do about it? Mod 1.21

**Comment by ArcticWah** [comment]
> this is intentionally changed so that people don't randomly edit other people's genders. (and cuz it made others uncomfortable)

**Comment by DeGamingDerpy** [comment]
any chance for a plugin to be added so we can see what other players have set up as settings for them. i play on a single player world with my gf. any change i can see them without making my server modded

**Comment by Betawolfy** [comment]
@DeGamingDerpy i didn't quite understand.. what do you mean "a plugin" in a singleplayer world ?
anyways, as far as I remember, there is a [Spigot plugin](https://modrinth.com/plugin/female-gender-spigot/) for servers with spigot in it.

**Comment by DeGamingDerpy** [comment]
o thx. i didnt know that. than im all happy. thx :)

**Comment by TSB-inc** [comment]
Maybe there is some way to change settings for other players only on the client side? (so that other changes are not displayed)
