### ISSUE TITLE
issue in forge 1.20.1 wildfirebreastpresetlist

### ISSUE THREAD

**Issue by destroyac** [WildfireRomeo/WildfireFemaleGenderMod#205]
title. here:

Errors:

Description	Resource	Path	Location	Type
Bound mismatch: The type WildfireBreastPresetList.BreastPresetListEntry is not a valid substitute for the bounded parameter <E extends AbstractSelectionList.Entry<E>> of the type AbstractSelectionList<E>	WildfireBreastPresetList.java	/WildfireFemaleGenderMod-forge-1.20.1/src/main/java/com/wildfire/gui	line 32	Java Problem

Description	Resource	Path	Location	Type
The method mouseClicked(double, double, int) is undefined for the type Object	WildfireBreastPresetList.java	/WildfireFemaleGenderMod-forge-1.20.1/src/main/java/com/wildfire/gui	line 145	Java Problem

Description	Resource	Path	Location	Type
The method mouseClicked(double, double, int) of type WildfireBreastPresetList.BreastPresetListEntry must override or implement a supertype method	WildfireBreastPresetList.java	/WildfireFemaleGenderMod-forge-1.20.1/src/main/java/com/wildfire/gui	line 140	Java Problem

Description	Resource	Path	Location	Type
The method render(GuiGraphics, int, int, int, int, int, int, int, boolean, float) of type WildfireBreastPresetList.BreastPresetListEntry must override or implement a supertype method	WildfireBreastPresetList.java	/WildfireFemaleGenderMod-forge-1.20.1/src/main/java/com/wildfire/gui	line 123	Java Problem

Description	Resource	Path	Location	Type
The return types are incompatible for the inherited methods ContainerEventHandler.children(), AbstractSelectionList<WildfireBreastPresetList.BreastPresetListEntry>.children()	WildfireBreastPresetList.java	/WildfireFemaleGenderMod-forge-1.20.1/src/main/java/com/wildfire/gui	line 32	Java Problem

Description	Resource	Path	Location	Type
The return types are incompatible for the inherited methods ContainerEventHandler.getFocused(), AbstractSelectionList<WildfireBreastPresetList.BreastPresetListEntry>.getFocused()	WildfireBreastPresetList.java	/WildfireFemaleGenderMod-forge-1.20.1/src/main/java/com/wildfire/gui	line 32	Java Problem

Description	Resource	Path	Location	Type
The type AbstractSelectionList.Entry is not visible	WildfireBreastPresetList.java	/WildfireFemaleGenderMod-forge-1.20.1/src/main/java/com/wildfire/gui	line 97	Java Problem

Im kinda new to java programming, but i wanted to change the max breast size limit to 3, and i getting this errors :(

**Comment by WildfireRomeo** [comment]
This isn't an issue with the mod itself if you were trying to change stuff. It's probably a game version / mod version problem. Closing.
