### ISSUE TITLE
(1.21) Breasts render with low light level compared to rest of model with the paper doll in the Legacy4J Mod.

### ISSUE THREAD

**Issue by JuniperIsSleepy** [WildfireRomeo/WildfireFemaleGenderMod#211]
This issue is not present in 1.20.1, but appears to have become a problem after the mod received major changes. Asked Legacy4J dev and they said only vanilla methods are used for rendering so it is not on their end. 
![Screenshot_2024-08-08_231107](https://github.com/user-attachments/assets/af01d9a7-83c2-4693-9ef8-fdf17e9b2bc8)

**Comment by WildfireRomeo** [comment]
I'm not sure if this is something I can fix.
