### ISSUE TITLE
Gender change for other players 1.21

### ISSUE THREAD

**Issue by TSB-inc** [WildfireRomeo/WildfireFemaleGenderMod#213]
On version 1.21, the ability to open the visual gender change menu for other players (for example, on the server) has disappeared. Please return the ability to change the gender of other players on the client's side (so that only the one who set the settings can see them)

**Comment by Kichura** [comment]
No. and it's because this feature made other people uncomfortable with having their genders changed unwantedly.

**Comment by TSB-inc** [comment]
> No. and it's because this feature made other people uncomfortable with having their genders changed unwantedly.

So if another player with the mod changes the settings for himself, will other players with the mod see it?

**Comment by Shlyapa-V-Shlyape** [comment]
i hate this new update
