### ISSUE TITLE
[Feature Request] Support every 1.20.x [Forge/Fabric] With the Same Features

### ISSUE THREAD

**Issue by HazeWorksOnFiveMServer** [WildfireRomeo/WildfireFemaleGenderMod#216]
Title says everything :>

**Comment by Betawolfy** [comment]
Uh not really. I don't personally understand. Would you like to give more indications of what you are requesting?

**Comment by WildfireRomeo** [comment]
I'm only working on the most recent Minecraft version for this mod. Any new features added to the mod will have to be backported by other individuals if they want it on older versions.
