### ISSUE TITLE
[CurseForge Issue Report] Female hurt sound doesn't play after eating an enchanted golden apple (possibly when under any effect)

### ISSUE THREAD

**Issue by WildfireRomeo** [WildfireRomeo/WildfireFemaleGenderMod#22]
**Pomi108**

Steps to reproduce:

1) Enable the female hurt sounds in your character settings

2) Eat a golden apple

3) Jump off a cliff

4) Listen to the regular fleshy hurt sound playing

**Comment by Kichura** [comment]
Can reproduce on latest version of this mod.

**Comment by WildfireRomeo** [comment]
Cannot reproduce in latest version
