### ISSUE TITLE
Unable to edit other people.

### ISSUE THREAD

**Issue by RobinCrafter** [WildfireRomeo/WildfireFemaleGenderMod#222]
Hello, so we have a server and there is no button for me to change other people. My friend also tried it and it didn't work.

![Bez názvu](https://github.com/user-attachments/assets/6acd6fd4-2c1d-4227-8892-07402dde9f9a)

**Comment by Kichura** [comment]
Works as intended, and it's because this feature made other people uncomfortable with having their genders changed unwantedly.
