### ISSUE TITLE
how to disable cloud on 1.21 version?

### ISSUE THREAD

**Issue by goddamntoaster** [WildfireRomeo/WildfireFemaleGenderMod#259]
I play on vanilla server, so I want to manually change options for other players how I did on 1.20.x

**Comment by goddamntoaster** [comment]
> You can't edit other people

but it could be done on the old version, I had to choose the gender for the players myself

**Comment by WildfireRomeo** [comment]
That has not been a feature for more than half a year. It was removed. To answer your question: Click the cloud icon to view the cloud menu to disable it.

**Comment by goddamntoaster** [comment]
![2024-12-08_20 29 21](https://github.com/user-attachments/assets/28af2c18-a846-471a-a950-4af6c97d9387)
I don't have it in menu :/

**Comment by WildfireRomeo** [comment]
What version of the mod are you using? That mod version doesn't have Cloud Syncing.

**Comment by goddamntoaster** [comment]
1.21.1 from Modrinth

**Comment by WildfireRomeo** [comment]
Mod version, not Minecraft version.

but regardless, the editing of other players hasn't been in the mod since like 1.18.

**Comment by goddamntoaster** [comment]
oh, it is 3.2.1 version of mod

**Comment by Betawolfy** [comment]
> oh, it is 3.2.1 version of mod

The cloud isn't in the mod's 3.2.1 version, as it was introduced in 4.0.

**Comment by goddamntoaster** [comment]
> > oh, it is 3.2.1 version of mod
> 
> The cloud isn't in the mod's 3.2.1 version, as it was introduced in 4.0.

so why I don't have this menu?
(screenshot taken from minecraft version 1.20.1, mod version 3.0.1)
![2024-12-12_12 43 13](https://github.com/user-attachments/assets/5ea4ab16-d118-4273-a931-bfda1814b9e3)
if there is no cloud, so this menu should be here

**Comment by Betawolfy** [comment]
> > > oh, it is 3.2.1 version of mod
> > 
> > 
> > The cloud isn't in the mod's 3.2.1 version, as it was introduced in 4.0.
> 
> so why I don't have this menu? (screenshot taken from minecraft version 1.20.1, mod version 3.0.1) ![2024-12-12_12 43 13](https://private-user-images.githubusercontent.com/83985208/395098966-5ea4ab16-d118-4273-a931-bfda1814b9e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMDI0ODgsIm5iZiI6MTczNDAwMjE4OCwicGF0aCI6Ii84Mzk4NTIwOC8zOTUwOTg5NjYtNWVhNGFiMTYtZDExOC00MjczLWE5MzEtYmZkYTE4MTRiOWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDExMTYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZGQ5NGEyOGM3ZmVkNmM3YTVlODc0NmM0NmFjODBhZjFiMTRkY2VlOGU5YjQwOTNkNzY5ZjBhYjVmMGExODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J57EJlYB3Cf75ay81zRWmkFy-Map59opB1RBKA4VR1g) if there is no cloud, so this menu should be here

What you're showing is the menu that allows you to edit another player's breasts. This has nothing to do with Cloud.
This player menu has been removed in 3.1, a.k.a Minecraft 1.20.2 version update. *

**Comment by goddamntoaster** [comment]
> > > > oh, it is 3.2.1 version of mod
> > > 
> > > 
> > > The cloud isn't in the mod's 3.2.1 version, as it was introduced in 4.0.
> > 
> > 
> > so why I don't have this menu? (screenshot taken from minecraft version 1.20.1, mod version 3.0.1) ![2024-12-12_12 43 13](https://private-user-images.githubusercontent.com/83985208/395098966-5ea4ab16-d118-4273-a931-bfda1814b9e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMDI0ODgsIm5iZiI6MTczNDAwMjE4OCwicGF0aCI6Ii84Mzk4NTIwOC8zOTUwOTg5NjYtNWVhNGFiMTYtZDExOC00MjczLWE5MzEtYmZkYTE4MTRiOWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDExMTYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZGQ5NGEyOGM3ZmVkNmM3YTVlODc0NmM0NmFjODBhZjFiMTRkY2VlOGU5YjQwOTNkNzY5ZjBhYjVmMGExODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J57EJlYB3Cf75ay81zRWmkFy-Map59opB1RBKA4VR1g) if there is no cloud, so this menu should be here
> 
> What you're showing is the menu that allows you to edit another player's breasts. This has nothing to do with Cloud. This player menu has been removed in 3.1, a.k.a Minecraft 1.20.2 version update. *

yeah, i was js wondering: ig there is no menu, so maybe it is cloud-based now (before I read patchnotes). Sooooo, how an i change another players breasts on this version?

**Comment by Betawolfy** [comment]
> yeah, i was js wondering: if there is no menu, so maybe it is cloud-based now (before I read patchnotes). Sooooo, how an i change another players breasts on this version?

If the mod is installed on both the server and the client (for all players), you should be able to see other players' breasts.
Otherwise, you can't.
The only way would be to play with config files.
The cloud has been implemented recently in 1.20.3-1.20.4, and updates are not backported to older versions.
