### ISSUE TITLE
[Suggestion] Customizeable Defaults

### ISSUE THREAD

**Issue by sisby-folk** [WildfireRomeo/WildfireFemaleGenderMod#40]
Hey hi! I'm a pack dev and I'd love to ship with a config that, as an example, defaults players to "Other", with chest size 0%, and vanilla's neutral hurt sounds. 

As such, I'd love it if there was a defaults config for players who's configurations aren't initialised yet!

[NB: Technically, I'd be sated by the mod having this always be the default, or dropping the M/F/O presets entirely - but I understand that my preferences aren't everyone's preferences, and that the presets have a positive effect for some folks 😌]

**Comment by alxpettit** [comment]
the male/female option doesn't seem to have any functional purpose. Also, there's men with breasts, and women without them -- and enbies are a thing too! :P

Seems a lil silly to gender this.
