### ISSUE TITLE
Sliders not saving or adjusting properly

### ISSUE THREAD

**Issue by InkyLily** [WildfireRomeo/WildfireFemaleGenderMod#41]
Hey, I saw this issue get brought up before but couldn't find the fix anywhere or the version that was talked about. This is on forge version 40.1.0.

The issue is that the sliders are not adjusting values as they should, nor are they saving values correctly either. This could be an issue with one of the other mods within the pack I'm running but I don't think any of them really mess with player model besides adjusting the size of the model.

**Comment by 3x1t-5tyl3** [comment]
https://github.com/baileyholl/Ars-Nouveau/issues/519

**Comment by Moonspire** [comment]
I've had this issue and went through my mod list and discovered that Union Lib breaks Wildfire's Gender Mod's gui sliders. If you have it in your pack InkyLily then try removing it and any mods that require it (Burden of Time, Survive for example)

**Comment by InkyLily** [comment]
>
It was Ars-Nouveau, but that is something to keep in mind
