### ISSUE TITLE
Suggestion to use "less gendered" terminology in-game.

### ISSUE THREAD

**Issue by Lylythii** [WildfireRomeo/WildfireFemaleGenderMod#43]
While it's clear the intent of this mod is to allow individuals to better express themselves, I noticed the usage of "Female" & "Male" terms being used over somewhat "less gendered" terms like "Fem" & "Masc" (or potentially other more suitable terms).

This might cause discomfort for individuals who identify in other ways, or not at all. (Eg: Non-binary), especially considering the "default gender" in-game is set to "Male". & is also something that's not very apparent in modpacks.

**Comment by murdercube** [comment]
Breasts pertain more towards female biology than femininity.  Also, nobody beyond your small online echo chambers cares about your misguided politics surrounding gender, and you'd do well to remember that.

**Comment by SheepSwindler** [comment]
> > Breasts pertain more towards female biology than femininity. Also, nobody beyond your small online echo chambers cares about your misguided politics surrounding gender, and you'd do well to remember that.
> 
> do i smell a terf?
> 
> i may disagree with using less gendered terms bc we hav "Other" already, but ill let u know i am a _guy_ born a _guy_ and i got tits. also _guys_ can get _breast_ cancer, so how do they _not_ hav breasts?

He didn't say guys don't have breasts the only reason you have tits Is cause you're fat.

**Comment by Aiden-crypto-ai** [comment]
> do i smell a terf?
> 
> i may disagree with using less gendered terms bc we hav "Other" already, but ill let u know i am a _guy_ born a _guy_ and i got tits. also _guys_ can get _breast_ cancer, so how do they _not_ hav breasts?

Terf? That applies to women not being included in the struggle for womens rights? Does the brony not know the difference between a terf and a regular person with common sense? Does the transfem non binary male passing obese slug not comprehend that gynecomastia is a medical condition and rare at that? That'd be like asking for an intersex option in every game. Its too uncommon for them to care. "but its for inclusivity" don't care, didn't ask, plus you're either obese or have a medical condition.

**Comment by WildfireRomeo** [comment]
Locking this, don't argue about this over GitHub... Bring it to personal conversations or something.

However to answer the original suggestion: I'm going to be leaving it as "Male/Female/Other". Using the terms "Feminine/Masculine" just doesn't sound right to me personally. If you don't want to be classified as male or female, choose other as the option.
