### ISSUE TITLE
[1.18.2] Crash when interacting with Immersive Engineering tanks

### ISSUE THREAD

**Issue by Shedao-Shai** [WildfireRomeo/WildfireFemaleGenderMod#47]
Forge: 40.1.31
Wildfire: 2.9
Immersive Engineering: 8.0.1-147

Crash log: https://gist.github.com/Shedao-Shai/67a14ce26027bedbfec54b18ee251a95

What happened: Filling a bucket from an Immersive Engineering tank causes a crash and wildfire is mentioned in the crash log, leading me to believe that wildfire is having an odd interaction. I believe this is originating from a sound event somehow

**Comment by pupnewfster** [comment]
I believe that issue was fixed by #39 so mostly just need to wait until wildfire releases an update.

**Comment by PDelta41** [comment]
I had the same issue; it also caused some issues with Survive purified water, and Tinker's Construct tanks
Attached is my crash report:
[crash-2022-07-07_20.57.15-client.txt](https://github.com/WildfireRomeo/WildfireFemaleGenderMod/files/9068902/crash-2022-07-07_20.57.15-client.txt)
t

**Comment by Waterspark63** [comment]
Same think happens with Industrial Foregoing. I think any mod with tanks has this issue.
Here's my crash log
[crash-2022-08-01_04.35.44-client.txt](https://github.com/WildfireRomeo/WildfireFemaleGenderMod/files/9240518/crash-2022-08-01_04.35.44-client.txt)
.

**Comment by wardmatt1** [comment]
I am also having this issue. [My crash log](https://pastebin.com/BdfgdXUa)

**Comment by WildfireRomeo** [comment]
Fixed in Forge [Mod Version 2.9.1](https://www.curseforge.com/minecraft/mc-mods/female-gender-forge/files/3920306)
