### ISSUE TITLE
[Suggestion/Cosmetic Armor quirk] Armor "Physics Resistance" toggle

### ISSUE THREAD

**Issue by ArgobargSoup** [WildfireRomeo/WildfireFemaleGenderMod#49]
I hope I'm getting this right, as it's kind of both a suggestion for the mod by itself and a quirk with the Cosmetic Armor mod...

The new armor physics resistance effect, which reduces bounce, is a nice touch, but it would be neat if it could be on a toggle, or perhaps a slider.

The part where Cosmetic Armor comes in, and part of the reason I'm suggesting the toggle/slider, is that the bounce reduction still takes effect if the armor's invisible, if the armor's in the main slot.

Testing in a world with just the Gender mod and cosmetic armor, 1.18.2, Forge 40.1.0:

-Diamond armor in main slot, cosmetic slot empty, armor visible:  No bounce
-Diamond armor in main slot, cosmetic slot empty, armor invisible:  No bounce
-Main slot empty, diamond armor in cosmetic slot, armor visible:  No bounce
-Main slot empty, diamond armor in cosmetic slot, armor invisible:  Bounce

Further testing:

-Diamond armor in main slot, leather armor in cosmetic slot, armor visible:  No bounce
-Leather armor in main slot, diamond armor in cosmetic slot, armor invisible:  Leather level of bouncing

Also in Forge 40.1.31

...minor note, if such a toggle/slider *is* added, and/or this mod interaction quirk fixed, it would be nice if it made it to the 1.18 version of the mod as well as the upcoming 1.19 version.  >w>

**Comment by Shedao-Shai** [comment]
I have encountered a similar issue in 1.19.2: even with breast physics enabled, there is no movement regardless of if the chestplate is visible or not. Probably a separate issue and I will file a report for it

**Comment by WildfireRomeo** [comment]
Re-added physics override a while ago.dsfs
