### ISSUE TITLE
[Fabric] Cosmetic Armor + Transparent Cosmetics issue

### ISSUE THREAD

**Issue by Daturachan** [WildfireRomeo/WildfireFemaleGenderMod#52]
Probably a duplicate of #21 but since that person didn't specify whether they were using Forge or Fabric, I thought I'd open a new issue. My deepest apologies if this was unnecessary 😅 

When wearing a _Transparent Cosmetics_ Transparent Chestplate in the Cosmetic trinket slot, the breasts still use the non-cosmetic armor texture instead of the invisible cosmetic one.

I'm having the exact same issue with any armor using the vanilla model.
Did not test with modded armors (MC Dungeon Armors, Gobber 2, Botania,...) since I've yet to come across one 😛 
I'll update this post later when I do.

This is using [Wildfire's Female Gender Mod](https://modrinth.com/mod/female-gender) v2.9 for Fabric in conjunction with [Cosmetic Armor](https://modrinth.com/mod/cosmetic-armor) v1.3.1 and [Transparent Cosmetics ](https://modrinth.com/mod/transparent-cosmetics) v1.4.0.

Here's an [Imgur album](https://imgur.com/a/cfdDtvK) detailing the issue.

Thank you for your work! ❤️

**Comment by WildfireRomeo** [comment]
Supposedly fixed in [Version 2.9.1 for MC 1.18.2](https://www.curseforge.com/minecraft/mc-mods/female-gender-fabric/files/3923378), please test it to make sure it works properly.

**Comment by Daturachan** [comment]
Here are my test results: 

- **Vanilla** - OK.
- **AdventureZ** - OK.
- **Additional Additions** - OK.
- **Advanced Reborn** - OK.
- **Advanced Netherite** -OK.
Chestplates don't render on the breasts, even with no Transparent Chestplate equipped, but this already happened before.
Note: this mod's chestplates use a custom model, not the vanilla one.
- **BetterEnd** - OK.
- **Bewitchment** - OK.
Breasts still appear pure magenta (texture error) when equipping a robe with no Transparent Chestplate equipped, but this already happened before.
Note: this mod's robes use a custom model.
- **Botania** - OK.
Breasts still appear pure magenta (texture error) when equipping a chestplate with no Transparent Chestplate equipped, but this already happened before.
Note: this mod's chestplates use a custom model, not the vanilla one.
- **Deep Mob Learning : Refabricated** - OK.
- **DragonLoot** - OK.
- **Dustrial Decor** - OK.
- **Exline's Copper Equipment** - OK.
- **Gear Reborn** - OK.
- **Gobber2** - OK.
- **MC Dungeons Armors** - OK.
- **Modern Industrialization** - OK.
- **Spectrum** - OK.
- **Tech Reborn** - OK.
- **The Twilight Forest** - OK.
Breasts still appear pure magenta (texture error) when equipping a chestplate with no Transparent Chestplate equipped, but this already happened before.
Amusingly, whereas this mod's armors didn't get hidden at all even with a Transparent Chestplate equipped, the breasts part now gets correctly hidden 😄 
Note: this mod's chestplates use a custom model, not the vanilla one.

As far as I'm concerned, this bug has been fixed since the oddities I've encountered only happen with chest pieces using a custom model, and those have always had compatibility issues with your mod.

Thanks again for taking the time to fix this! 💖
