### ISSUE TITLE
[1.19] Forge breaking changes

### ISSUE THREAD

**Issue by Baggytrousers27** [WildfireRomeo/WildfireFemaleGenderMod#56]
Forge 41.0.94+ (Also Forge 41.0.64 but that's another matter entirely)
Female-Gender-Mod-forge-1.19-3.0.0

Sided setup phase java.lang.NoClassDefFoundError: net/minecraftforge/client/ClientRegistry

[crashlog](https://github.com/WildfireRomeo/WildfireFemaleGenderMod/files/9127010/crash-2022-07-17_13.49.56-fml.txt)

Dunno how fabric functions but working with forge seems ... fun.

**Comment by Kichura** [comment]
#55.

**Comment by WildfireRomeo** [comment]
Fixed in latest Forge version [(3.0.1)](https://www.curseforge.com/minecraft/mc-mods/female-gender-forge/files/3920268).
