### ISSUE TITLE
how to fix this problem?it just crash after i open the game

### ISSUE THREAD

**Issue by MyD1Man** [WildfireRomeo/WildfireFemaleGenderMod#60]
Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
Install fabric, version 0.47.9 or later.
Unmet dependency listing:
<html>Mod 'Wildfire's Female Gender<br>Mod' (wildfire_gender) 1.19-3.0.0 requires version 0.47.9 or later of fabric, which is missing!</html>

**Comment by Kichura** [comment]
You need fabric api for 1.19.

**Comment by MyD1Man** [comment]
ok, let me try again
