### ISSUE TITLE
2.9.1 version crashes on world start up. 

### ISSUE THREAD

**Issue by Fade-Alchemist** [WildfireRomeo/WildfireFemaleGenderMod#62]
if I load with the previous version of this mod, the world loads normally. I get the following crash if I update to 2.9.1 and make no other changes. Mods are listed in the crash report. 

[crash-2022-08-09_00.53.18-client.txt](https://github.com/WildfireRomeo/WildfireFemaleGenderMod/files/9287349/crash-2022-08-09_00.53.18-client.txt)

**Comment by starlesskye** [comment]
did you find a fix to this issue?

**Comment by WildfireRomeo** [comment]
Closing as 1.18.2 is no longer supported.
