### ISSUE TITLE
Breasts don't show for other players

### ISSUE THREAD

**Issue by TheEternalAce** [WildfireRomeo/WildfireFemaleGenderMod#69]
I'm on a server with the mod installed on both the clients and the server however the breasts don't change for other players.

**Comment by TheEternalAce** [comment]
Btw I'm on the 1.16.5 forge version

**Comment by TheEternalAce** [comment]
And the server is on Aternos if that matters

**Comment by VirtualLusamine** [comment]
im having the exact same proglem but im using sparked host so i doubt its about the server host
but the thing is it just doesnt show to me and one other player
because one of them can see every one so i imagine its a player by player thing and i have no idea wtf it could be

**Comment by Kichura** [comment]
Please try updating to the latest 1.19 version to see if your issue persists there.

**Comment by TheEternalAce** [comment]
But ther server is 1.16.5...

**Comment by TheEternalAce** [comment]
and I don't want to lose mods that haven't been ported yet

**Comment by VirtualLusamine** [comment]
dude pixelmon only has for 1.16
there is a reason we havent updated to 1.19 XD

**Comment by TheEternalAce** [comment]
Huh?

**Comment by TheEternalAce** [comment]
um

**Comment by WildfireRomeo** [comment]
Since this report is for Minecraft 1.16.5, I'm not providing support for it. That version is too outdated
