### ISSUE TITLE
armor physics dose not work

### ISSUE THREAD

**Issue by cimu233** [WildfireRomeo/WildfireFemaleGenderMod#70]
After equipping the breastplate, the physics disappears, even though I have the armor physics turned on

**Comment by GayRedPanda** [comment]
Armor Physics don't really work with Iron, Diamond or Netherite, mostly to make it a little more realistic. The Physics only work for Leather, Gold and maybe Chainmail. I'd have to check it though

**Comment by quakeman00** [comment]
same issue here, the armor physic option is enabled tho, and still dosent work, this might make sence when the armor is visible but on our sever has cosmetic armor and visual allowing us to hide and swap armor for cosmetic stuff or just hide armor, and now the girls have rigid chest.

**Comment by WildfireRomeo** [comment]
Armor physics have gone a rework and the physics toggle button really doesn't serve a purpose anymore. I'm probably going to remove it next update.
