### ISSUE TITLE
Game soft crash when taking damage

### ISSUE THREAD

**Issue by NotAF2P** [WildfireRomeo/WildfireFemaleGenderMod#73]
For some reason, whenever I take any form of damage the game gives me a server crash screen.
![Screenshot (5)](https://user-images.githubusercontent.com/96606399/192137826-dcc9377a-365d-4142-a305-41d117fdfea1.png)
I have tested just this mod and the issue remains. I have version 3.0.0 and fabric 0.61.0

**Comment by nyaambxr** [comment]
Duplicate of #57
