### ISSUE TITLE
feature request: hide boob armor

### ISSUE THREAD

**Issue by VerserVarlin** [WildfireRomeo/WildfireFemaleGenderMod#75]
i have a mod that hides the armor on the player. the only issue is the gender mod shows armor on the breast. i would like to have a button/ option to turn off the armor on the breast so it shows the texture underneath. i would be very happy if this became a feature.

**Comment by terminal-cs** [comment]
this would be quite clunky to have as a user-exposed option, the mod should detect when your mod has that option enabled and disable breast armor accordingly

**Comment by StellarWitch7** [comment]
Are you talking about this mod, @VerserVarlin?
https://github.com/WildfireRomeo/WildfireFemaleGenderMod/issues/74

**Comment by StellarWitch7** [comment]
Because if you were, I've just got news that its author fixed the issue in version 1.6.6 for 1.19.4 and 1.20 Fabric.
