### ISSUE TITLE
crash on 1.16.5 with mahou tsukai

### ISSUE THREAD

**Issue by stepsword** [WildfireRomeo/WildfireFemaleGenderMod#77]
[crash-2022-10-16_23.51.58-client.txt](https://github.com/WildfireRomeo/WildfireFemaleGenderMod/files/9796789/crash-2022-10-16_23.51.58-client.txt)

Hi, I'm the Mahou Dev, someone sent me this crash log. Not sure if you're still doing dev for 1.16.5 or not, and its possible this is fixed on later versions already. Looks like just a null check somewhere

**Comment by WildfireRomeo** [comment]
Late reply, but 1.16.5 is no longer supported so I am closing this issue.
