### ISSUE TITLE
My minecraft dont launch with this mod (fabric)

### ISSUE THREAD

**Issue by BendyKrowside** [WildfireRomeo/WildfireFemaleGenderMod#81]
![Screenshot_6](https://user-images.githubusercontent.com/117937106/201168494-665c986c-0b6e-4659-a9c2-b27b3d36080c.png)

**Comment by BendyKrowside** [comment]
I'm running minecraft and it just throws this error (even if the mod is the only one)

**Comment by GayRedPanda** [comment]
Like the Fabric window says, you gotta update your Fabric to 0.47.9 or later. I'd also recommend downloading the newest version of the Mod (At least if you're on 1.19.2

**Comment by Infinidoge** [comment]
Unfortunately the mod ID involved makes it a bit hard to understand, this is really saying that you need to install `fabric-api`, of at least that version.

**Comment by terminal-cs** [comment]
> Unfortunately the mod ID involved makes it a bit hard to understand, this is really saying that you need to install `fabric-api`, of at least that version.
> 
> You can find Fabric API here for download: https://modrinth.com/mod/fabric-api

are you sure it's that? from what i've seen the fabric api is labled as Fabric-API

**Comment by RacoonDog** [comment]
> are you sure it's that? from what i've seen the fabric api is labled as Fabric-API

the change to `fabric-api` is still pretty recent, and `fabric` is still provided by fabric api for compatibility reasons

that being said, wfgm uses `fabric` to refer to fabric api 
https://github.com/WildfireRomeo/WildfireFemaleGenderMod/blob/268a7042eaa2b7bee70dbd76a15eba1289d0acc9/src/main/resources/fabric.mod.json#L39 

so yes, the fix here is to install fabric api
