### ISSUE TITLE
Fabric 1.18.2 2.9.1 version missing from curseforge

### ISSUE THREAD

**Issue by skyenyaa** [WildfireRomeo/WildfireFemaleGenderMod#85]
I was reading the issue thread for cosmetic armor and I found the link to the supposed 2.9.1 version that fixed the issue, but it appears the page does not exist anymore. Is there anyway I can get a link to the download? Thank you for your time and hard work! 💗

**Comment by WildfireRomeo** [comment]
https://www.curseforge.com/minecraft/mc-mods/female-gender-fabric/files/3923378
