### ISSUE TITLE
Lag Spikes and Log Spam

### ISSUE THREAD

**Issue by DocWhoSonicDrive** [WildfireRomeo/WildfireFemaleGenderMod#86]
So, using this on a modded fabric server with multiple armor types. I have seen that there's an error with missing textures that's been reported, however this is a different types of error. 
If someone has armor equipped that has multiple layers, my minecraft log is spammed with a message that contains "net.minecraft.class_151: Non [a-z0-9_.-] character in namespace of location:"
I can provide the complete mod list if necessary, but here are the pastebins for the errors that repeat with different armor sets.
https://pastebin.com/pD9tMrNz  - Quantum armor from _TechReborn_
https://pastebin.com/vHhEiu8U   - Netherite-Diamond armor from _Advanced Netherite_

**Fabric version:** 0.14.10
**MC version:** 1.19.2
**Mod version:** 3.0.1

**Extra info**: I can wear armor myself and not get the error except in F5 mode. It doesn't matter what settings the person has, as long as the textures from the GenderMod (the breasts obviously) are rendered (>0% on sliders and actually toggled). I am using MultiMC launcher, as referenced in the logs.
GPU, CPU, and RAM memory are seemingly unaffected.
A similar issue is
https://pastebin.com/3dqDN0FT - Jet Suit from _Ad Astra!_
but it doesn't seem to cause random lag spikes and leads to the missing texture (pink material) bug.

**Comment by xyxt1c** [comment]
I have a similar problem with TechReborn armor. It constantly spams something like: [Log](https://paste.gg/p/xystemat1c/e28a463ffcce48d79607cb011c0e459f)

and eats round about 20-25 FPS on a rather old CPU if the breast model is active. Deactivating the breast models or using vanilla chestplates solves the issue.
