### ISSUE TITLE
Breast position

### ISSUE THREAD

**Issue by JesseHelmes** [WildfireRomeo/WildfireFemaleGenderMod#89]
Add compatibility for mods that can change the size of the body and allows the player to lay on its back.
So when you lay on your back that the breasts do not disappear into the body and the same for when the player grows as for when the player becomes small they will hang in the air.

So you probably have to check the body angle and body size and put the breasts on a fixed point of the body and make them grow depending on the body size.

I am not sure if the breast grows with the body, it is something that i thought it won't.
as for the laying part, i saw in a roleplay server that when i used a lay command that it did not showed the breast.

getWhiteOverlayProgress is not being applied to the breasts

**Comment by TransBluelight** [comment]
I don't know what mod you were using for changing your character size but it had no issues with character size on Pehkui... It only had issues with size for me back on 1.16.5 with More Player Models but that mod's been stuck on 1.16.5 for a while now anyway and Wildfire doesn't support the 1.16.5 version of the gender mod anymore.
