### ISSUE TITLE
texture bug thing 

### ISSUE THREAD

**Issue by epicGamingA** [WildfireRomeo/WildfireFemaleGenderMod#90]
so I hvae the Pym tech mod on if I put on a suit and have the mod on this happens 

![2023-01-17_16 54 42](https://user-images.githubusercontent.com/84932495/213010329-e531926d-b037-4812-a9ef-94ce33c8b40f.png)

**Comment by epicGamingA** [comment]
image not working hold on

**Comment by WildfireRomeo** [comment]
Not going to fix, as Pym Tech's latest version is 1.16.5.
