### ISSUE TITLE
1.19.3 .jar file for fabric?

### ISSUE THREAD

**Issue by ZtrukRuhtra** [WildfireRomeo/WildfireFemaleGenderMod#96]
No idea if this is something i'm just getting outright wrong, I'm a major newbie, no coder at all and and i'm only trying to get a updated version since my friend's asking, i went to the 1.19.3 fabric fork and couldn't compile it so i'm only asking for this since I can't seem to do it myself lol
thanks in advance if anyone actually helps out on this

**Comment by WildfireRomeo** [comment]
Officially released now.
https://modrinth.com/mod/female-gender/version/IJqeWuFk
